### ISSUE TITLE
Install error? 

### ISSUE THREAD

**Issue by WahzooWiizard** [php-school/phpschool.io#134]
![Capture](https://user-images.githubusercontent.com/107349035/174459636-371b3134-f43b-459a-a11c-ac53621dc403.PNG)

So i got this

**Comment by AydinHassan** [comment]
Hi,

You will need to install those PHP extensions, but it will depend on your operating system how you install them. Which OS are you running on and how is PHP installed?

Probably the following command will help us:

```shell
which php
```
