### ISSUE TITLE
Update installation docs on homepage and install page to use workshop manager

### ISSUE THREAD

**Issue by AydinHassan** [php-school/phpschool.io#45]

**Comment by mikeymike** [comment]
@AydinHassan @OliverChenery 

Looking at this in more detail it looks a little more involved than anticipated. Because we now need to provide some install instructions (probably in terminal style) and we have the gif there I feel the design is going to need tweaking in some way. 

Thoughts?

**Comment by AydinHassan** [comment]
@mikeymike maybe you can sketch out what you thinking?

**Comment by AydinHassan** [comment]
Done
