### ISSUE TITLE
Poster for PHP MiNDS talk

### ISSUE THREAD

**Issue by AydinHassan** [php-school/phpschool.io#50]

**Comment by AydinHassan** [comment]
@mikeymike lets hangout Monday/Tuesday and sketch something out.

**Comment by OliverChenery** [comment]
@AydinHassan Doing this now for you guys. @mikeymike has given me a very detailed and descriptive sketch of how it should be… I especially like the "cool icons" and "funky background" labels haha

**Comment by AydinHassan** [comment]
@OliverChenery you are a hero, I love you

**Comment by OliverChenery** [comment]
Do you have copy for a bit of an intro? should about the event.

**Comment by AydinHassan** [comment]
Is what I wrote in #51 okay? That is for the PHP MiNDS site about the same event

**Comment by AydinHassan** [comment]
Done!
