### ISSUE TITLE
Intro talk

### ISSUE THREAD

**Issue by mikeymike** [php-school/phpschool.io#53]
Talk to be given at the event prior to our main event as a small intro as to what is happening.

**Comment by mikeymike** [comment]
##Game Plan  

* Homepage open, give brief info for those who don’t know what it is we do / are doing
* Explain the installation instructions
* Jump straight into the workshop-manager, install learnyouphp
* Pop it open, show it off a little
* Maybe ask someone to come up and write the solution to one and then verify
* Wrap up with details on main workshop and maybe unconf talk ?!?!

**Comment by AydinHassan** [comment]
Sounds good to me!
