### ISSUE TITLE
Increase performance of website

### ISSUE THREAD

**Issue by AydinHassan** [php-school/phpschool.io#56]
https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fwww.phpschool.io%2F

There are quite a few recommendations we can use to improve the performance of the site, anyone wanting to take a stab at this, feel free!

**Comment by OliverChenery** [comment]
@AydinHassan With the minified js and css now hopefully this should improve the page speed. We could also try to ass the css into a style tag in the head so that no request is made, shane showed me the Yes site he did the scored 100/100

**Comment by AydinHassan** [comment]
@OliverChenery sounds interesting, the rank has gone up quite a bit now :)
