### ISSUE TITLE
wrong year displaying on site footer

### ISSUE THREAD

**Issue by mrlami** [php-school/phpschool.io#97]
It's likely a non-php issue though since code below is correct

https://github.com/php-school/phpschool.io/blob/bcc2922ac6fbcd100734e1c724b78f4e15891cc3/templates/includes/footer.phtml#L4

**Comment by AydinHassan** [comment]
Interesting - thanks @mrlami - it's probably the cache, i'll flush it now.

**Comment by AydinHassan** [comment]
Also - seems the blog is generated on deploy, so i've redeployed. Looks fixed to me. feel free to reopen if you notice something is still wrong!
